.TH "xkb-switch" "1" "1.3.1" "J. Bromley, S. Mironov, Alexei Rad'kov" "User Commands"
.SH "xkb-switch"
.LP 
.B xkb\-switch
is a C++ program that allows to query and change the XKB layout state.
.SH "SYNTAX"
.LP 
xkb\-switch [options] 
.SH "DESCRIPTION"
.LP 
.B xkb\-switch
is a C++ program that allows to query and change the XKB layout state. Originally ruby\-based code written by J. Bromley.
.SH "OPTIONS"
.LP 
.TP 
\fB\-s\fR <layout>
Set current layout group to <layout>.
.TP 
.BR \-l ", "\-\^\-list
Display all layout groups.
.TP 
.BR \-h ", "\-\^\-help
Display a help message.
.TP 
.BR \-v ", "\-\^\-version
Show version number.
.TP 
.BR \-w " "[\-p] ", "\-\^\-wait " "[\-p]
Wait for group change and exits.
If \fB\-p\fR is specified, print the new layout group.
.TP 
.BR \-W
Infinitely wait for group change.
.TP 
.BR \-n ", " \-\^\-next
Switch to the next layout group.
.TP 
.TP 
.BR \-p
Display current layout group.
.TP 
.SH "AUTHORS"
.LP 
J. Bromley, S. Mironov, Alexei Rad'kov
